[package]
name = "rupit"
description = "simple cli tool to run long terminal commands by aliases"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
